apiVersion: v1
replicaCount: 2
namespace: default
metaLabels:
  - name: domain
    value: tools
ingress:
  name: kubelens-api-ingress
  host: api.kubelens.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
configMap:
  mountPath: "config"
image:
  repository: docker.io/kubelens/kubelens-api
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  enableTLS: false
  port: 80
  containerPort: 39000
  annotations:
    app.kubernetes.io/name: kubelens-api
    app.kubernetes.io/instance: kubelens-api
    app.kubernetes.io/version: latest
  livenessProbePath: /healthcheck
  readinessProbePath: /healthcheck
resources:
  requests:
    cpu: 125m
    memory: 512M
  limits:
    cpu: 250m
    memory: 1G
